version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: email-portal-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: email-portal
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - email-portal-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: email-portal-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:adminpassword@mongodb:27017/email-portal?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      JWT_EXPIRE: 30d
      DIRECTADMIN_URL: ${DIRECTADMIN_URL}
      DIRECTADMIN_USERNAME: ${DIRECTADMIN_USERNAME}
      DIRECTADMIN_PASSWORD: ${DIRECTADMIN_PASSWORD}
      DEFAULT_EMAIL_QUOTA: 1024
      PASSWORD_LENGTH: 16
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - email-portal-network
    volumes:
      - ./apps/backend/.env:/app/.env:ro

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000/api
    container_name: email-portal-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - email-portal-network

networks:
  email-portal-network:
    driver: bridge

volumes:
  mongodb_data: